export enum CarClassEnum {
  StockCarBrasil2022 = 1,
  StockCarBrasil2021 = 2,
  StockCarBrasil2020 = 3,
  StockCarBrasil2019 = 4,
  GT5 = 5,
  GT4 = 6,
  GT3 = 7,
  GTE = 8,
  GTOpen = 9,
  P1 = 10,
  P2 = 11,
  P3 = 12,
  P4 = 13,
  DPi = 14,
  GroupC = 15,
  F3 = 16,
  FClassicGen1 = 17,
  FClassicGen2 = 18,
  FClassicGen3 = 19,
  FRetroGen1 = 20,
  FRetroGen2 = 21,
  FRetroGen3 = 22,
  FVee = 23,
  FTrainer = 24,
  FTrainerAdv = 25,
  FV10Gen1 = 26,
  FV10Gen2 = 27,
  FV12 = 28,
  FReiza = 29,
  FUltimate2019 = 30,
  FUltimate2022 = 31,
  CaterhamAcademy = 32,
  CaterhamSuperlight = 33,
  CaterhamSupersport = 34,
  Caterham620R = 34,
  PorscheCarreraCup = 35,
  ARCCamaro = 36,
  CopaClassicB = 37,
  CopaClassicFL = 38,
  CopaFusca = 39,
  CopaTruck = 40,
  CopaUno = 41,
  HotCars = 42,
  StockCarBrasil1999 = 43,
  OldStock = 44,
  StockCarBrasil1979 = 45,
  StockCarBrasil1986 = 46,
  MontanaCup = 47,
  MiniChallenge = 48,
  LancerCup = 49,
  M1ProCar = 50,
  SprintRace = 51,
  TouringCar60 = 52,
  TouringCar60Gen2 = 53,
  TouringCar70 = 54,
  GroupA = 55,
  SuperV8 = 56,
  G40JuniorCup = 57,
  G55Supercup = 58,
  KartRental = 59,
  KartShifter = 60,
  Kart125cc = 61,
  KartGX390 = 62,
  Superkart = 63,
  StreetCars = 64,
  TSICup = 65,
  FUSAGen1 = 66,
  FUSAGen2 = 67,
  FUSAGen3 = 68,
  FVintage_Gen1 = 69,
  FVintage_Gen2 = 70,
  GT1 = 71
}

export const CarClassEnumLabel = new Map<CarClassEnum, string>([
  [CarClassEnum.ARCCamaro, 'Aussie Racing Cars - Camaro'],
  [CarClassEnum.CaterhamAcademy, 'Caterham Academy'],
  [CarClassEnum.CaterhamSuperlight, 'Caterham Superlight'],
  [CarClassEnum.CaterhamSupersport, 'Caterham Supersport'],
  [CarClassEnum.Caterham620R, 'Caterham 620R'],
  [CarClassEnum.CopaClassicB, 'Copa Classic B'],
  [CarClassEnum.CopaClassicFL, 'Copa Classic FL'],
  [CarClassEnum.CopaFusca, 'Copa Fusca'],
  [CarClassEnum.CopaTruck, 'Copa Truck'],
  [CarClassEnum.CopaUno, 'Copa Uno'],
  [CarClassEnum.DPi, 'DPi Prototype'],
  [CarClassEnum.F3, 'Formula 3'],
  [CarClassEnum.FClassicGen1, `Formula Classic '87 - Gen.1`],
  [CarClassEnum.FClassicGen2, `Formula Classic '88 - Gen.2`],
  [CarClassEnum.FClassicGen3, `Formula Classic '91 - Gen.3`],
  [CarClassEnum.FRetroGen1, `Formula Retro '74 - Gen.1`],
  [CarClassEnum.FRetroGen2, `Formula Retro '78 - Gen.2`],
  [CarClassEnum.FRetroGen3, `Formula Retro '83 - Gen.3`],
  [CarClassEnum.FVintage_Gen1, `Formula Vintage '67 - Gen.1`],
  [CarClassEnum.FVintage_Gen2, `Formula Vintage '69 - Gen.2`],
  [CarClassEnum.FV12, `Formula V12 1995`],
  [CarClassEnum.FV10Gen1, `Formula V10 '97 - Gen.1`],
  [CarClassEnum.FV10Gen2, `Formula V10 2000 - Gen.2`],
  [CarClassEnum.FReiza, `Formula Reiza`],
  [CarClassEnum.FUltimate2019, `Formula Ultimate 2019 Gen.1`],
  [CarClassEnum.FUltimate2022, `Formula Ultimate 2022 Gen.2`],
  [CarClassEnum.FTrainer, `Formula Trainer`],
  [CarClassEnum.FTrainerAdv, `Formula Trainer Advanced`],
  [CarClassEnum.FVee, `Formula Vee`],
  [CarClassEnum.FUSAGen1, `Formula USA '95 - Gen.1`],
  [CarClassEnum.FUSAGen2, `Formula USA '98 - Gen.2`],
  [CarClassEnum.FUSAGen3, `Formula USA '03 - Gen.3`],
  [CarClassEnum.G40JuniorCup, `Ginetta G40 Cup`],
  [CarClassEnum.G55Supercup, `Ginetta G55 Supercup`],
  [CarClassEnum.GT1, `GT1`],
  [CarClassEnum.GT3, `GT3`],
  [CarClassEnum.GT4, `GT4`],
  [CarClassEnum.GT5, `GT5`],
  [CarClassEnum.GTE, `GTE`],
  [CarClassEnum.GTOpen, `GT Open`],
  [CarClassEnum.GroupA, `Group A`],
  [CarClassEnum.GroupC, `Group C`],
  [CarClassEnum.HotCars, `Hot Cars`],
  [CarClassEnum.KartRental, `Kart Rental`],
  [CarClassEnum.Kart125cc, `Kart 125cc`],
  [CarClassEnum.KartShifter, `Kart Shifter`],
  [CarClassEnum.KartGX390, `Kart GX390`],
  [CarClassEnum.Superkart, `SuperKart`],
  [CarClassEnum.LancerCup, `Lancer Cup`],
  [CarClassEnum.M1ProCar, `M1 ProCar`],
  [CarClassEnum.MiniChallenge, `JCW Mini Challenge`],
  [CarClassEnum.MontanaCup, `Copa Montana`],
  [CarClassEnum.P1, `P1 Prototype`],
  [CarClassEnum.P2, `P2 Prototype`],
  [CarClassEnum.P3, `P3 Prototype`],
  [CarClassEnum.P4, `P4 Prototype`],
  [CarClassEnum.SprintRace, `Sprint Race Cup`],
  [CarClassEnum.OldStock, `Old Stock Opala`],
  [CarClassEnum.StockCarBrasil1979, `Stock Car Brasil 1979`],
  [CarClassEnum.StockCarBrasil1986, `Stock Car Brasil 1986`],
  [CarClassEnum.StockCarBrasil1999, `Stock Car Brasil 1999`],
  [CarClassEnum.StockCarBrasil2019, `Stock Car Brasil 2019`],
  [CarClassEnum.StockCarBrasil2020, `Stock Car Brasil 2020`],
  [CarClassEnum.StockCarBrasil2021, `Stock Car Brasil 2021`],
  [CarClassEnum.StockCarBrasil2022, 'Stock Car Brasil 2022'],
  [CarClassEnum.StreetCars, 'Street Car'],
  [CarClassEnum.SuperV8, 'V8 Supercars'],
  [CarClassEnum.TouringCar60, 'Touring Car 60s'],
  [CarClassEnum.TouringCar60Gen2, 'Touring Car 60s - 2'],
  [CarClassEnum.TouringCar70, 'Touring Car 70s'],
  [CarClassEnum.TSICup, 'Vokswagen TSI Cup'],
])
